CREATE TABLE users (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    role VARCHAR(100) NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

CREATE TABLE classes (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    class_id VARCHAR(20) UNIQUE NOT NULL,
    teacher_id INTEGER NOT NULL REFERENCES users(id)
);

CREATE TABLE class_student (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    class_id INTEGER NOT NULL REFERENCES classes(id),
    student_id INTEGER NOT NULL REFERENCES users(id)
);

CREATE TABLE year (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    year INTEGER NOT NULL,
    year_group INTEGER NOT NULL
);

CREATE TABLE public_holidays (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    year_id INTEGER NOT NULL REFERENCES year(id),
    name VARCHAR(100) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL
);

CREATE TABLE events (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    year_id INTEGER NOT NULL REFERENCES year(id),
    class_id INTEGER NOT NULL REFERENCES classes(id),
    name VARCHAR(100) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL
);
